#-------------------------------------------------------------------------------
# Build & Test for pushes and pull requests on the main branch.
# (In theory only pull requests should happen on the main branch.)
# Run all unit tests and integration tests.
#-------------------------------------------------------------------------------
name: Microservice Y

#-------------------------------------------------------------------------------
# Triggers
#-------------------------------------------------------------------------------
on:
  push:
    branches:
      - main
    paths:
      - 'MicroserviceY/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - 'MicroserviceY/**'
      - '.github/workflows/**'


#-------------------------------------------------------------------------------
# Jobs
#-------------------------------------------------------------------------------
jobs:  
  build-test:
    uses: ./.github/workflows/dotnet-unit-integration-tests-workflow.yml
    with:
      service-path: MicroserviceY
      runs-on: ubuntu-latest
      dotnet-version: "10.0.x"
      configuration: "Release"